### ISSUE TITLE
Formatting on Study

### ISSUE THREAD

**Issue by Meechmo** [glutanimate/mini-format-pack#1]
## Prerequisite checklist

* [Yes] In case of a bug: Have you tried restarting Anki?
* [Yes] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [Yes] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [Yes] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

Hi I'm using Anki and this format pack to study for veterinary school exams. I am mainly using the bullet points from this pack. The formatting works great when I am creating the cards - however, when I go to study mode, for some reason, the bullet points are lined up on the edge but all of the words are centered on the page which kind of defeats the purpose of having bullet points. Here is a screenshot of what is happening. 
![image](https://user-images.githubusercontent.com/43627012/46118477-8f2df900-c1bb-11e8-8f98-8c5dc046f03f.png)

[Be as specific as possible. Provide screenshots if you think they can help.]

## How can we reproduce the problem?
I guess just create cards with bullet points and check them in study mode. 

[What were you doing when the problem occurred?]

1. I was studying using custom study when the issue appeared

**Expected behavior:** [What you expected to happen] Expected bullets to format like a normal bullet list like in Word

**Actual behavior:** [What actually happened] Bullets were right aligned but words were centered on the page

**Reproducible?:** [Can you reliably reproduce the issue by following the steps above?] Yes

## Version information

**Anki**

[Please head to *Help* → *About Anki* and Paste the version string here, e.g.:]

Version 2.1.4
Qt 5.9.2 PyQt 5.9

**System**
MacOS
- Operating system: [Windows/**macOS**/Linux]
- Version: [e.g. 10, High Sierra, Ubuntu 18.04]

**Comment by AwesomeLemon** [comment]
This is exactly the problem I have. (Version 2.1.6, if it matters).

@Meechmo , could you please tell me if you've managed to fix the issue somehow, or maybe if you have found an alternative addon that supports bulletpoints?

**Comment by glutanimate** [comment]
Guys, this doesn't have anything to do with the add-on. By default this is how Anki formats `ul` and `.ol` elements (unordered and ordered HTML lists). To change this you will have to update the styling of your card templates, e.g. by adding:

```css
ul, ol {
   text-align:left;
}
```

to the styling section.

For more information please see here:

https://chrisk91.me/2018/09/28/Anki-Templates-Introduction-HTML.html

https://chrisk91.me/2018/09/19/Basic-CSS-Template-for-Anki.html

**Comment by AwesomeLemon** [comment]
Thank you, it worked.

However, this was entirely non-obvious to Anki newbie like me. Maybe you could add it to ReadMe?
In any case, thank you for the addon and for the answer.

**Comment by glutanimate** [comment]
Yeah, you're right. When you've been using Anki for a while it's sometimes easy to forget how idiosyncratic it can be for new users. I've added this to my todo list.
