### ISSUE TITLE
404 Error when downloading

### ISSUE THREAD

**Issue by evanscho** [glutanimate/mini-format-pack#3]
## What is the problem/feature you would like to see fixed/implemented?

404 Error when downloading in Anki 2.1

## How can we reproduce the problem?

1. In Anki desktop: Tools -> Add-Ons -> Browse & Install
2. Enter Code for Mini Format Pack (295889520) and click Enter

**Expected behavior:** Installation

**Actual behavior:** "Download failed: Error downloading: 404"

**Reproducible?:** Yes

## Version information

**Anki**

Version 2.0.52
Qt 4.8.2 PyQt 4.9.4

**System**

- Operating system: macOS
- Version: Mojave 10.14.1

**Comment by glutanimate** [comment]
Hi Evan,

Thanks for the report. Download errors are usually not specific to
individual add-ons, but rather the result of connectivity issues between
your computer and AnkiWeb.

The best way to resolve these is to report them on the Anki support forums.
However, before you do that you should definitely give the download another
try (if you haven't done so already). Issues like these can sometimes be
transient.

Also, please check if downloading other add-ons works fine, and if so make
sure to include that information in your report on the Anki forums.

evanscho <notifications@github.com> schrieb am Mi., 19. Dez. 2018, 22:19:
