### ISSUE TITLE
Does the add-on work for 2.1.66 version of Anki?

### ISSUE THREAD

**Issue by helitopia** [glutanimate/mini-format-pack#34]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### Your question

**My setup:**
Version ⁨2.1.66 (70506aeb)⁩
Python 3.9.15 Qt 6.5.2 PyQt 6.5.2

When installing add-on by its code I have an error `One or more errors occurred: 295889520: Invalid code, or add-on not available for your version of Anki.`

Cannot understand what is wrong. 
Tried updating to 23.10, installed the add-on succesfully. But right now Syntax Highlighting for Code plugin (1463041493) is not working on the new Anki version, so I have to stay on latest up to 23.10 - 2.1.66. Downgraded to it again and have the following message in add-ons window:
![image](https://github.com/glutanimate/mini-format-pack/assets/92454023/72a73a0c-2083-4eef-a8b1-cb34fe39559f)

**Comment by glutanimate** [comment]
Hi there, thanks for the report! It looks like the branches were not set up correctly. It should be fixed now, so if you attempt to download the add-on again, it should work.

**Comment by helitopia** [comment]
Thanks, much appreciated
