### ISSUE TITLE
indent does not work with hotkeys

### ISSUE THREAD

**Issue by fischbone** [glutanimate/mini-format-pack#4]
## Prerequisite checklist

* [x] In case of a bug: Have you tried restarting Anki?
* [x] Are you running the latest version of the add-on. Have you redownloaded the add-on from AnkiWeb to make sure?
* [x] Did you check the add-on documentation (e.g. AnkiWeb description, Wiki if it exists) for known issues?
* [x] Did you perform a cursory search through the existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
The indent and outdent shortcuts (ctrl+shift+[ and ctrl +shift+] ) do not work for me, I have tried it on multiple keyboards and that is not the issue, I can also achieve that formatting by clicking on the button with the mouse but not via the hotkeys.  

[Be as specific as possible. Provide screenshots if you think they can help.]

## How can we reproduce the problem?

type anything
hold ctrl + [ to create a list
hold ctrl+ shift + [ to try to indent that list
see if it works

[What were you doing when the problem occurred?]

1. [First step]
2. [Second step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

hotkey would perform indent/outdent

**Actual behavior:** [What actually happened]

hotkey does not perform indent/outdent

**Reproducible?:** [Can you reliably reproduce the issue by following the steps above?]

yes on my machine, not sure if it is machine specific for some reason

## Version information
Not sure where to find this, but I installed it off ankiweb on 2/17

**Anki**
Version 2.1.8 (71e0c880)
Qt 5.12.0 PyQt 5.11.3

[Please head to *Help* → *About Anki* and Paste the version string here, e.g.:]

[Version 2.0.47]
[Qt 4.8.1 PyQt 4.9.1]

**System**
Windows 10

- Operating system: [Windows/macOS/Linux]
- Version: [e.g. 10, High Sierra, Ubuntu 18.04]

**Comment by glutanimate** [comment]
Hi. Thanks for the detailed bug report. A few questions:

- What keyboard layout are you using? E.g.: On a German keyboard you might have to use the AltGr key to get to the `[`, which usually stops keyboard shortcuts from working. This is not an issue on the QWERTY layout which most Anki users will be using.
- And as a follow-up to that: Have you tried changing the hotkeys in the add-on's configuration? The add-on is fully customizable to account for region- and OS-specifis key conflicts.

**Comment by fischbone** [comment]
Sorry, this is not a problem with your add-on. I tracked down that this was actually an issue with AutoHotKey having a rival hotkey action.
It's now working correctly. Thanks for your great work!
