### ISSUE TITLE
Numbered lists & bullet points are off-centre from other text

### ISSUE THREAD

**Issue by Krakyn** [glutanimate/mini-format-pack#7]
Hey! I made an account just to report this and hopefully get it fixed. Thanks for your efforts!

See screenshot attached.

Text in the numbered lists is off-centre with other text. It would be nice to have this aligned.

![image](https://user-images.githubusercontent.com/54581534/63767307-a667f000-c910-11e9-9188-33c80a291c16.png)

**Comment by glutanimate** [comment]
Hey Krakyn,

Thanks for the detailed report!

Please see my answer here: https://www.reddit.com/r/Anki/comments/cs04ev/_/exbe0eo

**Comment by Krakyn** [comment]
Wow you are an absolute legend - thank you for replying so quickly! Looking forward to seeing more of your anki work in the future (particularly better tags for 2.1)

**Comment by Krakyn** [comment]
For future reference (to anyone who might read this), inserting the following into my note type format fixed the issue and centered the list text:

ul {
     display:table; margin:0 auto;
}
li {
    margin-right: 40px;
}

Fiddle with the 40px value until its centered for you.
