### ISSUE TITLE
Crash when saving a card

### ISSUE THREAD

**Issue by Jasonium17** [glutanimate/mini-format-pack#8]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I installed both the main add-on and the supplementary app.  When I try to save a card, this happens.

It also happens when I click Browse from the main part of the app (not within a card set yet).  It works if I click Browse once I am in a card set.

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.14 (7b93e985) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=1
Add-ons possibly involved: Mini Format Pack Supplementary

Caught exception:
  File "aqt/webview.py", line 27, in cmd
  File "aqt/webview.py", line 87, in _onCmd
  File "aqt/webview.py", line 368, in _onBridgeCmd
  File "aqt/toolbar.py", line 56, in _linkHandler
  File "aqt/toolbar.py", line 74, in _browseLinkHandler
  File "aqt/main.py", line 855, in onBrowse
  File "aqt/__init__.py", line 82, in open
  File "aqt/browser.py", line 407, in __init__
  File "aqt/browser.py", line 642, in setupEditor
  File "aqt/editor.py", line 53, in __init__
  File "aqt/editor.py", line 96, in setupWeb
  File "anki/hooks.py", line 39, in runFilter
  File "/Users/jasonschultz/Library/Application Support/Anki2/addons21/476705431/__init__.py", line 309, in addMyButton
    return buttons + [editor._addButton(os.path.join(os.path.dirname(__file__),"icons\\pre.png"),"button_wrap_pre","Add pre tag for selected text"),
  File "aqt/editor.py", line 149, in _addButton
  File "aqt/editor.py", line 123, in resourceToData
<class 'FileNotFoundError'>: 
#### Checklist

I disabled the supplementary app and everything works fine.  

Mainly I want numbered lists with left justification and was hoping the supplementary add-on dealt with that.

Thanks.

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've verified that I use the latest version of Anki by checking at https://apps.ankiweb.net#download
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### Information about your Anki set-up

*Please fill out the section corresponding with your Anki version:*

##### If you are using Anki 2.1

*Please open Anki, go to Help → About, click on "Copy Debug Info", and paste the result between the backticks below (if the button does not appear you are using an older version of Anki 2.1 and will need to update first):*

```

```

#####  If you are using Anki 2.0

*Please open Anki, go to Help → About, find the two lines starting with `Version:` and `Qt`, and copy-paste them between the backticks below:*

```

```

*Please fill in details about your operating system (Windows/macOS/Linux, which version):*

- OS:
- version:

*Please open Anki, go to Tools → Add-ons, take a screenshot of your installed add-ons, and paste it below:*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```python

```

**Comment by glutanimate** [comment]
Hi Jasonium,

I'm afraid I'm not the author of the supplementary add-on, so there's not much I can do to help here. My recommendation would be to try and get in touch with the creator of that add-on and report the issue to them: https://ankiweb.net/shared/info/476705431
